### ISSUE TITLE
Menu entry "Open on Github" still visible in Menu/Packages when package is deactivated

### ISSUE THREAD

**Issue by ManuelTS** [atom/open-on-github#108]
I only use shell scripts when it comes to Github, so I have all Github packages in Atom deactivated. But the menu entry "Open on Github" is still visible in Menu/Packages.

**Comment by rsese** [comment]
Thanks for the report - can you fill in the issue template details just so we have all the basic details like what version of Atom you're running and what operating system you're on?

Also, I'm assuming you're reporting that the menu item is still available right after disabling the package, but it's not there after you restart Atom (this is the behavior I see on macOS 10.12.6 with Atom 1.30.0-nightly14).
