### ISSUE TITLE
default to master when open an unpublished branch

### ISSUE THREAD

**Issue by DepthDeluxe** [atom/open-on-github#27]
After using this plugin for a little while, it has started to bother me that I can't open files that are in unpublished repositories.  The plugin generates the URL for where the branch should be but GitHub returns a 404 (obviously).  It would be nice for this plugin to default to opening on the master branch if a user is currently in one that's unpublished.

A quick and dirty way to do this would be to check the list of available branches to see if `$BRANCH` has a corresponding `remotes/origin/$BRANCH` in the branch list.

**Comment by kalimar** [comment]
:+1:

**Comment by kevinsawicki** [comment]
I believe this has now been fixed by #52
