### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by TheChymera** [atom/open-on-github#34]
Hi, I recently started using atom, and all the commands from this package seem to do nothing - how exactly is atom supposed to know at what URL the GitHub correspondent of each of my files is located?

**Comment by kankaristo** [comment]
Currently, `open-on-github` is broken because of this issue: https://github.com/atom/atom/issues/6335.

It's working if your default browser is Chrome, but not if it's Chromium (on Ubuntu, at least).

**Comment by kevinsawicki** [comment]
Closing this question out.
