### ISSUE TITLE
Cannot disable package

### ISSUE THREAD

**Issue by TheLastProject** [atom/open-on-github#41]
Somehow, clicking the disable button doesn't do anything. It does react to clicks in the sense of becoming dark gray when clicked, but doesn't actually get disabled. No output is printed to the console.

![disable_button](https://cloud.githubusercontent.com/assets/1885159/7068020/d3d0eb12-decf-11e4-9ddf-4b1bf8929c3e.png)

Atom version: 0.190.0-d9f0f23 (compiled from the latest release)
open-on-github version: 0.36.0
OS: Gentoo GNU/Linux

Other packages can be disabled without issue.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, it will be fixed in the next Atom release, 0.191
