### ISSUE TITLE
Setting to change the remote used for Copy URL and File

### ISSUE THREAD

**Issue by CraigCottingham** [atom/open-on-github#45]
It looks like the Copy URL and File commands get the Github URL from the `origin` remote. I would like to be able to specify a different remote, or (better yet) an ordered list to try.

**Comment by rgmccaw** [comment]
:+1:

**Comment by pluff** [comment]
@CraigCottingham isn't https://github.com/atom/open-on-github#remote-url-detection is what you were looking for?

**Comment by CraigCottingham** [comment]
@pluff It looks like it might be. To be honest, it's been so long since I filed this issue that I don't fully remember my use case, and I don't think I have the open-on-github plugin installed at the moment. I'll give it a try at my first opportunity.

**Comment by CraigCottingham** [comment]
@pluff It doesn't appear to be working. The file `.git/config` contains this:

```
[atom "open-on-github"]
    remote = upstream
```

but when I choose any of the subitems in `Packages > Open On GitHub`, the page that opens in my browser is to the repository named by `origin`, not `upstream`.

`upstream` is a private repository, in case that makes a difference. (Come to think of it, I can probably test that myself with a fork of a public repository.)

**Comment by CraigCottingham** [comment]
It doesn't work if the repositories are public, either.

The contents of `.git/config` and the output of `git remote show upstream` can be seen at https://gist.github.com/CraigCottingham/17b610fb0cb443595c01

When I choose `Packages > Open On GitHub > File`, for instance, the URL that loads is https://github.com/CraigCottingham/kitchenplan/blob/master/Gemfile#L1

Atom 1.5.3, open-on-github 0.40.0 in case it matters.

**Comment by 50Wliu** [comment]
@CraigCottingham The feature is only in open-on-github 0.41.0 and above.  That means it'll be available starting in Atom 1.7.0.  If you really want it right now, you can `apm install open-on-github`, which will override the built-in version that comes with Atom 1.5.3.

**Comment by CraigCottingham** [comment]
Unfortunately, the latest version (1.0.0) doesn't work properly with Atom 1.5.3. Now when I try to open the file on Github I get `No repository found for path: /path/to/filename`.

Since I'm out on the bleeding edge here, I'm going to assume this works when used properly. :-) Thanks for reminding me of this issue and letting me know of the fix.
