### ISSUE TITLE
Open On GitHub isn't working at all on my CentOS 7 with Atom 1.0.19

### ISSUE THREAD

**Issue by a1exus** [atom/open-on-github#51]
I tried to click on anything under `Packages` -> `Open On GitHub` from Atom and nothing is happening, no error messages either.

My system:

```
[alexus@wcmisdlin02 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
[alexus@wcmisdlin02 ~]$ uname -a
Linux X 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[alexus@wcmisdlin02 ~]$ rpm -q atom
atom-1.0.19-0.1.fc21.x86_64
[alexus@wcmisdlin02 ~]$ 
```

How can I troubleshoot it?

**Comment by izuzak** [comment]
@a1exus Are you able to reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, can you share a link to the GitHub project which you're able to reproduce this with? Also, does this happen for every Git project you have locally or only some projects? Can you provide the exact steps to reproduce this, starting from a `git clone` command which clones a repository form GitHub, and provide a GIF which follows those steps and clearly demonstrates the problem (in safe mode)?

**Comment by a1exus** [comment]
I just [Downloaded .rpm](https://atom.io/download/rpm) and used GitHub project: [a1exus/raspberry-pi-find-ip-address](https://github.com/a1exus/raspberry-pi-find-ip-address). I'm able to reproduce it with `atom --safe` as well.

I did `git clone https://github.com/a1exus/raspberry-pi-find-ip-address`, then used `File` -> `Add Project Folder`, specified local folder (where I did git clone to).

**Comment by izuzak** [comment]
> I did git clone https://github.com/a1exus/raspberry-pi-find-ip-address, then used File -> Add Project Folder, specified local folder (where I did git clone to).

Strange, that works just fine for me.

Can you try navigating to the root directory of the clone in your terminal and then starting atom from that directory like this: `atom .`, and then try using the Open On GitHub commands and see if that works?

So, if you cloned to `~/projects/raspberry-pi-find-ip-address`, then cd into that directory, and start atom with `atom .` from there.

**Comment by a1exus** [comment]
I tried this:

```
[alexus@wcmisdlin02 Desktop]$ cd ~/raspberry-pi-find-ip-address/
[alexus@wcmisdlin02 raspberry-pi-find-ip-address]$ atom --safe .
[alexus@wcmisdlin02 raspberry-pi-find-ip-address]$ 
```

**Comment by izuzak** [comment]
Thanks, @a1exus. To be honest, I'm not really sure what might be causing problems there. Just to make sure -- you start Atom with `atom --safe .` while positioned at the root directory for that Git repository, you open a file from that project in Atom, then you run the "Open on GitHub: Open" command, and nothing happens? Can you share a GIF which demonstrates that exact behavior? Do you have any other packages installed (`apm list --installed`)?

**Comment by a1exus** [comment]
@izuzak I'm not sure how I can create animated GIF..

```
[alexus@wcmisdlin02 ~]$ cd raspberry-pi-find-ip-address/
[alexus@wcmisdlin02 raspberry-pi-find-ip-address]$ git pull
Already up-to-date.
[alexus@wcmisdlin02 raspberry-pi-find-ip-address]$ atom --safe .
[alexus@wcmisdlin02 raspberry-pi-find-ip-address]$ apm list --installed
/home/alexus/.atom/packages (0)
└── (empty)

[alexus@wcmisdlin02 raspberry-pi-find-ip-address]$ 
```
`Menu` -> `Packages` -> `Open on Git Hub` -> anything

**Comment by izuzak** [comment]
@a1exus Did you open a specific file after starting Atom but before executing an "Open on GitHub" command?

**Comment by a1exus** [comment]
uh huh! I think that did that, after opening any file and then trying same thing firefox opened up with github))

thanks!!

**Comment by izuzak** [comment]
Great. :)
