### ISSUE TITLE
open-on-github  keybindings blocking @sign on swiss keyboard

### ISSUE THREAD

**Issue by ehnydeel** [atom/open-on-github#53]
Hi there,

the package open-on-github keybindings blocking @ sign on swiss keyboard.
alt-g is the swiss key-combination to write an @-character. is there any posibility
to uninstall this package from atom.io or is there a workaround to disable the keybinding
from this package?

thanks

**Comment by 50Wliu** [comment]
Atom currently cannot handle foreign keyboard layouts correctly - please subscribe to atom/atom-keymap#35 for further updates (and also try the [keyboard-localization](https://atom.io/packages/keyboard-localization) package).

**Comment by wollio** [comment]
@ehnydeel Hello.
I know it is a bit late and probably you already found the solution.
If not, you can disable the key bindings by doing these steps:
- settings
- packages
- search for "open-on-github" and press the "settings" button
- disable the keybindings or define your own.

**Comment by ehnydeel** [comment]
@wollio Hi,
thanks for your solution. think problem is already solved with the newest atom release. keybindings are working now with swiss keyboards. thanks anyway

cheers
