### ISSUE TITLE
This package seems to be not working for me at all.

### ISSUE THREAD

**Issue by riguy724** [atom/open-on-github#58]
I've tried it in safe mode, and I've looked at the dev console while running the command and there seems to be no output, or action taken from anything.  Any suggestions on investigating further?

**Comment by riguy724** [comment]
Some information about my installation environment:
- OS x el capitan
- all applications installed using homebrew (google chrome, atom)
- standard .gitconfig with user and email

**Comment by riguy724** [comment]
Just thought I should mention, I wouldn't typically open a github issue for this, but this is a brand new OSx installation with extremely minimal modifications to the machine outside of using homebrew and apm.  I also fully intend on trying to resolve this if I can get some indication of what might be wrong.

**Comment by 50Wliu** [comment]
@riguy724 did you open a file (i.e. have it visible in the editor) before executing the `Open on Github` command?

**Comment by riguy724** [comment]
Yeah, I tried it with a number of different files, from different
repositories as well, public and private.

**Comment by lee-dohm** [comment]
Can you be specific as to what command did not work with repro steps? It would be a help if you included what repository it did not work with also.

Please refer to the [How do I submit a good bug report?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) section in the `CONTRIBUTING.md` for suggestions on other information to include.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/open-on-github/issues/58#issuecomment-160702866. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
