### ISSUE TITLE
Support GitHub wiki?

### ISSUE THREAD

**Issue by jonasws** [atom/open-on-github#63]
If one runs `open-on-github:file` while editing a file from a GitHub wiki, the file is not resolved correctly. Is this something we want for this package, or should it be placed in seperate package?

**Comment by lee-dohm** [comment]
Is there an easy way to tell that the file is from a GitHub wiki?

**Comment by jonasws** [comment]
From what I've seen one can check if the remote url is of the format `https://github.com/someuser/SomeRepo.wiki.git` or similar, depending on how it was cloned. If htis is possible, implementing this should be fairly simple.

**Comment by jonasws** [comment]
Gave it a go, and created the following: #64
