### ISSUE TITLE
Would like to config a remote that is being opened to

### ISSUE THREAD

**Issue by colbycheeze** [atom/open-on-github#65]
I currently have a project that has 3 remotes...and one of them is NOT Github (it's Gerrit)

I keep a copy of the codebase on Github enterprise and would like the command to open to that remote...but it defaults to trying origin which breaks (since it tries to go to Gerrit)

Anyway, not sure if that's a hard fix. Thanks!

**Comment by 50Wliu** [comment]
@colbycheeze Is https://github.com/atom/open-on-github#remote-url-detection what you're asking for?  If so, that should be available starting in Atom 1.7.0.

**Comment by colbycheeze** [comment]
nice! Yep that's it. When is the Atom 1.7.0 release expected to ship?

**Comment by 50Wliu** [comment]
There's no ETA yet, but 1.6.0 should be released soon (most likely within the next two weeks, but definitely don't take my word for it), and then you can install 1.7.0 beta if you want to.
