### ISSUE TITLE
URLs are in the https://username@github.com/user/project format

### ISSUE THREAD

**Issue by sgtsquiggs** [atom/open-on-github#72]
This is not a bug, but most likely a side-effect of how I have my private repositories checked out:

`https://sgtsquiggs@github.com/sgtsquiggs/private.git`

Using the open-on-github plugin generates URLs like

`https://sgtsquiggs@github.com/sgtsquiggs/private/blame/master/private/apps/thing/api.py#L558`

This in turn leads Safari to complain about a `POSSIBLE PHISHING SITE`, which I have to manually choose to ignore every single time.

Any way to have open-on-github strip away my username from the URL?

**Comment by gmathieu** [comment]
👍

**Comment by johnschult** [comment]
Any progress on this as a fix? It should not be dependent on a SSH git clone...

**Comment by zenz** [comment]
Anyone can told me the package path? I would like to modify it to fit my need first.
