### ISSUE TITLE
Open Actions Not Working

### ISSUE THREAD

**Issue by afrazkhan** [atom/open-on-github#87]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

### Description

Trying to perform any of the "open on Github" commands such as "Open on Github: File/Blame/History" do not work. Tried with both shortcuts and the menu.

Not sure when this stopped working, because I don't use it every day, but probably in the last month or so.

### Steps to Reproduce

1. Try to perform an action such as "Open on Github: File"

**Expected behavior:** File opens in web browser with appropriate page.

**Actual behavior:** Nothing. If you try on a file that has no repository, you do get the normal error message that the file isn't associated with a repo, so the action does appear to be triggered.

**Reproduces how often:** 100%

### Versions

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.10.1

**Comment by 50Wliu** [comment]
You're missing the following information:
* Atom version output (`atom --version`)
* OS version

**Comment by afrazkhan** [comment]
Here you go

```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
And what OS are you using?

**Comment by afrazkhan** [comment]
Sorry, OSX Seria

**Comment by afrazkhan** [comment]
This has now been resolved (somehow?), maybe because of changes in recent updates to Atom.
