### ISSUE TITLE
use project git if active pane is not the editor

### ISSUE THREAD

**Issue by UziTech** [atom/open-on-github#91]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the tree-view is the active pane nothing happens

### Steps to Reproduce

1. select a folder/file in the tree-view
2. run command `open-on-github:repository`

**Expected behavior:** [What you expect to happen]

The repository opens on github

**Actual behavior:** [What actually happens]

nothing

**Comment by 50Wliu** [comment]
I think I will wait for the Tree View API to land before working on this.

**Comment by UziTech** [comment]
The Tree View service API would be nice to use if the tree view is the pane that is focused. But The issue is a little broader than that.

If a different dock is focused without any tie to a file or repo than I feel like `open-on-github:repository` should guess as to which repo the user wanted to open rather than doing nothing. 

I feel like the best guess would be the repo for the first project folder, especially if there is only one project folder.

something like:

```javascript
if (!itemPath) {
  itemPath = atom.project.getPaths()[0];
}
```

**Comment by UziTech** [comment]
The tree-view has an [API](https://github.com/atom/tree-view#api)
