### ISSUE TITLE
No longer working with Gitlab

### ISSUE THREAD

**Issue by rahlzel** [atom/open-on-github#92]
### Description

Using Open With Github > File or Blame used to work perfectly fine with Gitlab, too. Now it results in this strange, CSS-lacking page: https://streamable.com/yonbf. Oddly enough, immediately reloading the page also causes it to fail, however, clicking on the URL (which highlights it) and then hitting ENTER causes it to work fine. Possibly a Gitlab issue?

### Steps to Reproduce

1. Click on a line in your code.
2. ``Alt+g, o`` to open it

**Expected behavior:** A non-broken page

**Actual behavior:** A broken page

**Reproduces how often:** 100%

### Versions

Package: 1.2.1
Atom: 1.18.0
Windows 7 64bit

**Comment by jasonrudolph** [comment]
@rahlzel: Thanks for reporting this issue. I attempted to reproduce it using the steps below, but it seems to be working as expected for me. Does this flow match the steps you're following? If not, can you share the specific steps you're following?

---

1. In the terminal:
    1. `git clone https://gitlab.com/failmap/admin.git`
    2. `cd admin`
    3. `atom .`
2. In Atom using open-on-github v1.2.1:
    1. Open `README.md`
    2. With my cursor on the first line of the file, hit `alt+g o`
    3. Observe that https://gitlab.com/failmap/admin/blob/master/README.md#L1 is opened in my browser

**Comment by rahlzel** [comment]
Forgot I had posted this.

I figured out that by selecting the URL by clicking on it and then hitting ENTER to get my browser to reload it, the page loaded fine. Clicking the Refresh/Reload Page button did not work, oddly.

However, this issue seems to be fixed now, which means it may have been Gitlab that was the culprit.

Thanks.
